variables:
  var-hubnetwork-region: canadacentral
  #var-hubnetwork-managementGroupId: BCHealth-NorthernHealth-Platform
  #var-hubnetwork-azfw-configurationFileName: hub-azfw/hub-network.parameters.json
  #var-hubnetwork-nva-configurationFileName: hub-nva/hub-network.parameters.json
  var-hubnetwork-ngfw-configurationFileName: hub-ngfw/hub-network.parameters.json
  var-hubnetwork-subscriptionId: ae84a0bd-7c13-4453-8557-71b544c64c81
  #var-hubnetwork-azfwPolicy-configurationFileName: hub-azfw-policy/azure-firewall-policy.parameters.json
  #var-logging-managementGroupId: BCHealth-Platform-Management
  var-logging-subscriptionId: ae84a0bd-7c13-4453-8557-71b544c64c81
  deploymentRegion: canadacentral
  #var-NHA-managementGroupId: BCHealth-NorthernHealth
  #var-BCH-managementGroupId: BCHealth
  #var-identity-managementGroupId: BCHealth-NorthernHealth-Platform
  #var-logging-diagnosticSettingsforNetworkSecurityGroupsStoragePrefix: pubsecnsg
  var-logging-configurationFileName: logging.parameters.json
  var-managementgroup-hierarchy: |-
    {
      "id": "50ad62e2-e38e-447b-bd1c-6243bfe8d2e3",
      "name": "Tenant Root Group",
      "children": [
        {
          "id": "BCHealth",
          "name": "BCHealth",
          "children": [
            {
              "id": "BCHealth-Platform",
              "name": "Platform",
              "children": [
                {
                  "id": "BCHealth-Platform-Management",
                  "name": "Management",
                  "children": []
                },
                {
                  "id": "BCHealth-Platform-Connectivity",
                  "name": "Connectivity",
                  "children": []
                },
                {
                  "id": "BCHealth-Platform-Identity",
                  "name": "Identity",
                  "children": []
                },
                {
                  "id": "BCHealth-Platform-SharedServices",
                  "name": "SharedServices",
                  "children": []
                },
                {
                  "id": "BCHealth-Platform-Security",
                  "name": "Security",
                  "children": []
                }
              ]
            },
            {
              "id": "BCHealth-NewSubscription",
              "name": "NewSubscription",
              "children": []
            },
            {
              "id": "BCHealth-FraserHealth",
              "name": "FraserHealth",
              "children": [
                {
                  "id": "BCHealth-FraserHealth-Platform",
                  "name": "Platform",
                  "children": []
                },
                {
                  "id": "BCHealth-FraserHealth-Application",
                  "name": "Application",
                  "children": [
                    {
                      "id": "BCHealth-FraserHealth-Application-Cloud",
                      "name": "Cloud",
                      "children": []
                    },
                    {
                      "id": "BCHealth-FraserHealth-Application-Hybrid",
                      "name": "Hybrid",
                      "children": []
                    },
                  ]
                },
                {
                  "id": "BCHealth-FraserHealth-Decommissioned",
                  "name": "Decommissioned",
                  "children": []
                }
              ]
            },
            {
              "id": "BCHealth-InteriorHealth",
              "name": "InteriorHealth",
              "children": [
                {
                  "id": "BCHealth-InteriorHealth-Platform",
                  "name": "Platform",
                  "children": []
                },
                {
                  "id": "BCHealth-InteriorHealth-Application",
                  "name": "Application",
                  "children": [
                    {
                      "id": "BCHealth-InteriorHealth-Application-Cloud",
                      "name": "Cloud",
                      "children": []
                    },
                    {
                      "id": "BCHealth-InteriorHealth-Application-Hybrid",
                      "name": "Hybrid",
                      "children": []
                    },
                  ]
                },
                {
                  "id": "BCHealth-InteriorHealth-Decommissioned",
                  "name": "Decommissioned",
                  "children": []
                }
              ]
            },
            {
              "id": "BCHealth-IslandHealth",
              "name": "IslandHealth",
              "children": [
                {
                  "id": "BCHealth-IslandHealth-Platform",
                  "name": "Platform",
                  "children": []
                },
                {
                  "id": "BCHealth-IslandHealth-Application",
                  "name": "Application",
                  "children": [
                    {
                      "id": "BCHealth-IslandHealth-Application-Cloud",
                      "name": "Cloud",
                      "children": []
                    },
                    {
                      "id": "BCHealth-IslandHealth-Application-Hybrid",
                      "name": "Hybrid",
                      "children": []
                    },
                  ]
                },
                {
                  "id": "BCHealth-IslandHealth-Decommissioned",
                  "name": "Decommissioned",
                  "children": []
                }
              ]
            },
            {
              "id": "BCHealth-MinistryOfHealth",
              "name": "MinistryOfHealth",
              "children": [
                {
                  "id": "BCHealth-MinistryOfHealth-Platform",
                  "name": "Platform",
                  "children": []
                },
                {
                  "id": "BCHealth-MinistryOfHealth-Application",
                  "name": "Application",
                  "children": [
                    {
                      "id": "BCHealth-MinistryOfHealth-Application-Cloud",
                      "name": "Cloud",
                      "children": []
                    },
                    {
                      "id": "BCHealth-MinistryOfHealth-Application-Hybrid",
                      "name": "Hybrid",
                      "children": []
                    },
                  ]
                },
                {
                  "id": "BCHealth-MinistryOfHealth-Decommissioned",
                  "name": "Decommissioned",
                  "children": []
                }
              ]
            },
            {
              "id": "BCHealth-NorthernHealth",
              "name": "NorthernHealth",
              "children": [
                {
                  "id": "BCHealth-NorthernHealth-Platform",
                  "name": "Platform",
                  "children": []
                },
                {
                  "id": "BCHealth-NorthernHealth-Application",
                  "name": "Application",
                  "children": [
                    {
                      "id": "BCHealth-NorthernHealth-Application-Cloud",
                      "name": "Cloud",
                      "children": []
                    },
                    {
                      "id": "BCHealth-NorthernHealth-Application-Hybrid",
                      "name": "Hybrid",
                      "children": []
                    },
                  ]
                },
                {
                  "id": "BCHealth-NorthernHealth-Decommissioned",
                  "name": "Decommissioned",
                  "children": []
                }
              ]
            },
            {
              "id": "BCHealth-ProvincialHealth",
              "name": "ProvincialHealth",
              "children": [
                {
                  "id": "BCHealth-ProvincialHealth-Platform",
                  "name": "Platform",
                  "children": []
                },
                {
                  "id": "BCHealth-ProvincialHealth-Application",
                  "name": "Application",
                  "children": [
                    {
                      "id": "BCHealth-ProvincialHealth-Application-Cloud",
                      "name": "Cloud",
                      "children": []
                    },
                    {
                      "id": "BCHealth-ProvincialHealth-Application-Hybrid",
                      "name": "Hybrid",
                      "children": []
                    },
                  ]
                },
                {
                  "id": "BCHealth-ProvincialHealth-Decommissioned",
                  "name": "Decommissioned",
                  "children": []
                }
              ]
            }
          ]
        }
      ]
    }
  var-logging-region: canadacentral
  var-identity-configurationFileName: identity.parameters.json
  var-identity-region: canadacentral
  var-identity-subscriptionId: ae84a0bd-7c13-4453-8557-71b544c64c81

