variables:
  #var-hubnetwork-region: canadacentral
  #var-hubnetwork-managementGroupId: Connectivity
  #var-hubnetwork-azfw-configurationFileName: hub-azfw/hub-network.parameters.json
  #var-hubnetwork-nva-configurationFileName: hub-nva/hub-network.parameters.json
  #var-hubnetwork-subscriptionId: 4fd845de-f6c8-4e6d-9a87-c21c4ebf7edd
  #var-hubnetwork-azfwPolicy-configurationFileName: hub-azfw-policy/azure-firewall-policy.parameters.json
  #var-logging-managementGroupId: Management
  var-logging-subscriptionId: 026bb6b5-ed13-40f2-b8fa-b5b987429cbb
  deploymentRegion: canadacentral
  var-NHA-managementGroupId: BCHealth-NorthernHealth
  #var-BCH-managementGroupId: BCHealth
  #var-identity-managementGroupId: Identity
  #var-logging-diagnosticSettingsforNetworkSecurityGroupsStoragePrefix: pubsecnsg
  var-logging-configurationFileName: logging.parameters.json
  var-managementgroup-hierarchy: |-
    {
              "id": "BCHealth-NorthernHealth",
              "name": "NorthernHealth",
              "children": [
                {
                  "id": "BCHealth-NorthernHealth-Platform",
                  "name": "Platform",
                  "children": []
                },
                {
                  "id": "BCHealth-NorthernHealth-Application",
                  "name": "Application",
                  "children": [
                    {
                      "id": "BCHealth-NorthernHealth-Application-Cloud",
                      "name": "Cloud",
                      "children": []
                    },
                    {
                      "id": "BCHealth-NorthernHealth-Application-Hybrid",
                      "name": "Hybrid",
                      "children": []
                    },
                  ]
                },
                {
                  "id": "BCHealth-NorthernHealth-Decommissioned",
                  "name": "Decommissioned",
                  "children": []
                },
                {
                  "id": "BCHealth-NorthernHealth-Sadbox",
                  "name": "Sadbox",
                  "children": []
                }
              ]
    }
  #var-logging-region: canadacentral
  #var-identity-configurationFileName: identity.parameters.json
  #var-identity-region: canadacentral
  #var-identity-subscriptionId: 2987c7a3-1e43-4b28-b983-ac0925e37d03

