variables:
  var-hubnetwork-region: canadacentral
  #var-hubnetwork-managementGroupId: BCHealth-NorthernHealth-Platform
  #var-hubnetwork-azfw-configurationFileName: hub-azfw/hub-network.parameters.json
  #var-hubnetwork-nva-configurationFileName: hub-nva/hub-network.parameters.json
  var-hubnetwork-ngfw-configurationFileName: hub-ngfw/hub-network.parameters.json
  var-hubnetwork-subscriptionId: ae84a0bd-7c13-4453-8557-71b544c64c81
  #var-hubnetwork-azfwPolicy-configurationFileName: hub-azfw-policy/azure-firewall-policy.parameters.json
  #var-logging-managementGroupId: Management
  var-logging-subscriptionId: ae84a0bd-7c13-4453-8557-71b544c64c81
  deploymentRegion: canadacentral
  #var-NHA-managementGroupId: BCHealth-NorthernHealth
  #var-BCH-managementGroupId: BCHealth
  #var-identity-managementGroupId: BCHealth-NorthernHealth-Platform
  #var-logging-diagnosticSettingsforNetworkSecurityGroupsStoragePrefix: pubsecnsg
  var-logging-configurationFileName: logging.parameters.json
  var-managementgroup-hierarchy: |-
    {
              "id": "BCHealth-NorthernHealth",
              "name": "NorthernHealth",
              "children": [
                {
                  "id": "BCHealth-NorthernHealth-Platform",
                  "name": "Platform",
                  "children": []
                },
                {
                  "id": "BCHealth-NorthernHealth-Application",
                  "name": "Application",
                  "children": [
                    {
                      "id": "BCHealth-NorthernHealth-Application-Cloud",
                      "name": "Cloud",
                      "children": []
                    },
                    {
                      "id": "BCHealth-NorthernHealth-Application-Hybrid",
                      "name": "Hybrid",
                      "children": []
                    },
                  ]
                },
                {
                  "id": "BCHealth-NorthernHealth-Decommissioned",
                  "name": "Decommissioned",
                  "children": []
                },
                {
                  "id": "BCHealth-NorthernHealth-Sadbox",
                  "name": "Sandbox",
                  "children": []
                }
              ]
    }
  var-logging-region: canadacentral
  var-identity-configurationFileName: identity.parameters.json
  var-identity-region: canadacentral
  var-identity-subscriptionId: ae84a0bd-7c13-4453-8557-71b544c64c81

