# ----------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, 
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
# OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
# ----------------------------------------------------------------------------------

name: 5 - VWAN Network with NVA

on:
  workflow_dispatch:
    
defaults:
  run:
    shell: pwsh
    working-directory: scripts/deployments

env:
  ENVIRONMENT_NAME: ${{ github.ref == 'refs/heads/main' && 'main' || 'lab'}}

jobs:
 vwan-network-with-nva:
    name: VWAN Network with NVA
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'main' || 'lab'}}

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure PowerShell modules
      run: |
        Install-Module Az -Force
        Install-Module powershell-yaml -Force

    - name: Deploy VWAN Network with NVA
      run: |
        ./RunWorkflows.ps1 `
          -DeployVWANNetworkWithNVA `
          -EnvironmentName '${{env.ENVIRONMENT_NAME}}' `
          -LoginServicePrincipalJson (ConvertTo-SecureString -String '${{secrets.ALZ_SPN_CREDENTIALS}}' -AsPlainText -Force) `
          -GitHubRepo ${env:GITHUB_REPOSITORY} `
          -GitHubRef ${env:GITHUB_REF} `
          -NvaUsername (ConvertTo-SecureString -String '${{secrets.PaloAltoPanorama_USERNAME}}' -AsPlainText -Force) `
          -NvaPassword (ConvertTo-SecureString -String '${{secrets.PaloAltoPanorama_PASSWORD}} '-AsPlainText -Force)